version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: prince_hunter_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - prince-hunter-net
    restart: always

  redis:
    image: redis:7-alpine
    container_name: prince_hunter_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redis_data:/data
    networks:
      - prince-hunter-net
    restart: always
    command: redis-server --appendonly yes

networks:
  prince-hunter-net:
    driver: bridge
